/* eslint-disable @next/next/no-img-element */
import React from 'react';
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Button, Checkbox, Form, Input } from 'antd';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [showPassword, setshowPassword] = React.useState(false)

  const onFinish=()=>{}


  return (
    <>
      <Head>
        <title>Lendsqr Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className={`${styles.main} ${inter.className}`}>
        
      </main> */}
     <nav className="navbar navbar-light bg-white mt-5 pt-5">
      <div className="container">
        <a className="navbar-brand" href="#">
          <img src="/images/logo.svg" alt="" className='img-fluid'/>
        </a>
      </div>
    </nav>
      <section className="container mt-5">
        <div className="row">
          <div className="col-md-6">
            <img src="/images/banner.svg" alt="" className='img-fluid mt-5'/>
          </div>
          <div className="col-md-5 offset-1">
            <h1>Welcome!</h1>
            <p className={`${styles.description} mb-5`}>Enter details to login.</p>

            <Form
              name="normal_login"
              className="login-form"
              initialValues={{ remember: true }}
              onFinish={onFinish}
            >
              <Form.Item
                name="email"
                rules={[{ required: true, message: 'Please input your Email!' }]}
              >
                <Input placeholder="Email" />
              </Form.Item>
              <Form.Item
                name="password"
                rules={[{ required: true, message: 'Please input your Password!' }]}
              >
                <div className="relative">
                  <Input
                    type={showPassword ? 'text' : "password"}
                    placeholder="Password"
                    autoComplete='new-password'
                  />
                  <p onClick={()=>setshowPassword(!showPassword)} className={`${styles.loginformforgot} ${styles.showText} cursor-pointer`}>{showPassword ? 'Hide' : 'Show'}</p>
                </div>
              </Form.Item>
              <Form.Item>
                <a className={styles.loginformforgot} href="">
                  Forgot password?
                </a>
              </Form.Item>

              <button className="login w-100 p-3">Log in</button>
            </Form>
          </div>
        </div>
      </section>
    </>
  )
}
