/* eslint-disable @next/next/no-img-element */
import React, { useEffect } from 'react';
import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import { Form, Input } from 'antd';
import { useUserContext } from '../context/UserContext';
import { v4 as uuidv4 } from 'uuid';
import { lsSet } from '../../helpers/functions';
import Router from 'next/router';
import { notification } from "antd";
import { ValidateUser } from '../../helpers/valiadte';


export default function Home() {

  const [showPassword, setshowPassword] = React.useState(false);
  const [loading, setLoading] = React.useState(false);

  const {usersState, setUsersState}=useUserContext();

  useEffect(() => {ValidateUser.validateUserLogin()},[]);

  const generateUserToken = () => {
    const userToken = uuidv4();
    // You can store or use the userToken as needed
    return userToken;
  };
  
  const onFinish=(val:any)=>{
    // Please note that in order to login, the email entered is checeked if it's among the list of user from the mock API.
    // If it exists, you can login with the an existing email and password of your choice. Thank you.
    try {
      const user = usersState.filter((user:any)=> user.email === val.email);
      const u = user[0];
      
      if(user.length > 0) {
        lsSet('token',  generateUserToken());
        lsSet('user', u);
        Router.push('/users');
      } else {
        notification.error({
          message: 'Email not found',
          description: 'Please enter with your correct email address',
        })
      }
    } catch(e) {
      console.log(e);
    }
  }


  return (
    <>
      <Head>
        <title>Lendsqr Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
     <nav className="navbar navbar-light bg-white mt-5 pt-5">
      <div className="container">
        <a className="navbar-brand" href="#">
          <img src="/images/logo.svg" alt="" className='img-fluid'/>
        </a>
      </div>
    </nav>
      <section className="container mt-5 mb-5">
        <div className="row">
          <div className="col-md-6">
            <img src="/images/banner.svg" alt="" className='img-fluid mt-5'/>
          </div>
          <div className="col-md-5 offset-md-1">
            <h1>Welcome!</h1>
            <p className={`${styles.description} mb-5`}>Enter details to login.</p>

            <Form
              name="normal_login"
              className="login-form"
              initialValues={{ remember: true }}
              onFinish={onFinish}
            >
              <Form.Item
                name="email"
                rules={[{ required: true, message: 'Please input your Email!' }]}
              >
                <Input placeholder="Email" />
              </Form.Item>
              <Form.Item
                name="password"
                rules={[{ required: true, message: 'Please input your Password!' }]}
              >
                <div className="relative">
                  <Input
                    type={showPassword ? 'text' : "password"}
                    placeholder="Password"
                    autoComplete='new-password'
                  />
                  <p onClick={()=>setshowPassword(!showPassword)} className={`${styles.loginformforgot} ${styles.showText} cursor-pointer`}>{showPassword ? 'Hide' : 'Show'}</p>
                </div>
              </Form.Item>
              <Form.Item>
                <a className={styles.loginformforgot} href="">
                  Forgot password?
                </a>
              </Form.Item>

              <button disabled={loading} className="login w-100 p-3">{loading ? 'Logging in...' : 'Log in'}</button>
            </Form>
          </div>
        </div>
      </section>
    </>
  )
}
